// Generated by `wit-bindgen` 0.44.0. DO NOT EDIT!
#include "env.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `emlite:env/host@0.1.0`

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-init-handle-table")))
extern void __wasm_import_emlite_env_host_emlite_init_handle_table(void);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-new-array")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_new_array(void);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-new-object")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_new_object(void);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-make-bool")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_make_bool(int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-make-int")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_make_int(int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-make-uint")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_make_uint(int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-make-bigint")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_make_bigint(int64_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-make-biguint")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_make_biguint(int64_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-make-double")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_make_double(double);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-make-str")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_make_str(uint8_t *, size_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-make-str-utf16")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_make_str_utf16(uint8_t *, size_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-get-value-bool")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_get_value_bool(int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-get-value-int")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_get_value_int(int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-get-value-uint")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_get_value_uint(int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-get-value-bigint")))
extern int64_t __wasm_import_emlite_env_host_emlite_val_get_value_bigint(int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-get-value-biguint")))
extern int64_t __wasm_import_emlite_env_host_emlite_val_get_value_biguint(int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-get-value-double")))
extern double __wasm_import_emlite_env_host_emlite_val_get_value_double(int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-get-value-string")))
extern void __wasm_import_emlite_env_host_emlite_val_get_value_string(int32_t, uint8_t *);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-get-value-string-utf16")))
extern void __wasm_import_emlite_env_host_emlite_val_get_value_string_utf16(int32_t, uint8_t *);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-typeof")))
extern void __wasm_import_emlite_env_host_emlite_val_typeof(int32_t, uint8_t *);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-push")))
extern void __wasm_import_emlite_env_host_emlite_val_push(int32_t, int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-get")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_get(int32_t, int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-set")))
extern void __wasm_import_emlite_env_host_emlite_val_set(int32_t, int32_t, int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-has")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_has(int32_t, int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-not")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_not(int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-is-string")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_is_string(int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-is-number")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_is_number(int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-is-bool")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_is_bool(int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-gt")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_gt(int32_t, int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-gte")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_gte(int32_t, int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-lt")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_lt(int32_t, int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-lte")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_lte(int32_t, int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-equals")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_equals(int32_t, int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-strictly-equals")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_strictly_equals(int32_t, int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-instanceof")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_instanceof(int32_t, int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-obj-call")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_obj_call(int32_t, uint8_t *, size_t, int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-obj-has-own-prop")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_obj_has_own_prop(int32_t, uint8_t *, size_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-construct-new")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_construct_new(int32_t, int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-func-call")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_func_call(int32_t, int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-inc-ref")))
extern void __wasm_import_emlite_env_host_emlite_val_inc_ref(int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-dec-ref")))
extern void __wasm_import_emlite_env_host_emlite_val_dec_ref(int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-throw")))
extern void __wasm_import_emlite_env_host_emlite_val_throw(int32_t);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-print-object-map")))
extern void __wasm_import_emlite_env_host_emlite_print_object_map(void);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-reset-object-map")))
extern void __wasm_import_emlite_env_host_emlite_reset_object_map(void);

__attribute__((__import_module__("emlite:env/host@0.1.0"), __import_name__("emlite-val-make-callback")))
extern int32_t __wasm_import_emlite_env_host_emlite_val_make_callback(int32_t, int32_t);

// Exported Functions from `emlite:env/dyncall@0.1.0`



// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void env_list_u16_free(env_list_u16_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint16_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void env_string_set(env_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void env_string_dup(env_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void env_string_free(env_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

void emlite_env_host_emlite_init_handle_table(void) {
  __wasm_import_emlite_env_host_emlite_init_handle_table();
}

uint32_t emlite_env_host_emlite_val_new_array(void) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_new_array();
  return (uint32_t) (ret);
}

uint32_t emlite_env_host_emlite_val_new_object(void) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_new_object();
  return (uint32_t) (ret);
}

uint32_t emlite_env_host_emlite_val_make_bool(bool v) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_make_bool(v);
  return (uint32_t) (ret);
}

uint32_t emlite_env_host_emlite_val_make_int(int32_t v) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_make_int(v);
  return (uint32_t) (ret);
}

uint32_t emlite_env_host_emlite_val_make_uint(uint32_t v) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_make_uint((int32_t) (v));
  return (uint32_t) (ret);
}

uint32_t emlite_env_host_emlite_val_make_bigint(int64_t v) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_make_bigint(v);
  return (uint32_t) (ret);
}

uint32_t emlite_env_host_emlite_val_make_biguint(uint64_t v) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_make_biguint((int64_t) (v));
  return (uint32_t) (ret);
}

uint32_t emlite_env_host_emlite_val_make_double(double v) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_make_double(v);
  return (uint32_t) (ret);
}

uint32_t emlite_env_host_emlite_val_make_str(env_string_t *s) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_make_str((uint8_t *) (*s).ptr, (*s).len);
  return (uint32_t) (ret);
}

uint32_t emlite_env_host_emlite_val_make_str_utf16(env_list_u16_t *s) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_make_str_utf16((uint8_t *) (*s).ptr, (*s).len);
  return (uint32_t) (ret);
}

bool emlite_env_host_emlite_val_get_value_bool(uint32_t h) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_get_value_bool((int32_t) (h));
  return ret;
}

int32_t emlite_env_host_emlite_val_get_value_int(uint32_t h) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_get_value_int((int32_t) (h));
  return ret;
}

uint32_t emlite_env_host_emlite_val_get_value_uint(uint32_t h) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_get_value_uint((int32_t) (h));
  return (uint32_t) (ret);
}

int64_t emlite_env_host_emlite_val_get_value_bigint(uint32_t h) {
  int64_t ret = __wasm_import_emlite_env_host_emlite_val_get_value_bigint((int32_t) (h));
  return ret;
}

uint64_t emlite_env_host_emlite_val_get_value_biguint(uint32_t h) {
  int64_t ret = __wasm_import_emlite_env_host_emlite_val_get_value_biguint((int32_t) (h));
  return (uint64_t) (ret);
}

double emlite_env_host_emlite_val_get_value_double(uint32_t h) {
  double ret = __wasm_import_emlite_env_host_emlite_val_get_value_double((int32_t) (h));
  return ret;
}

void emlite_env_host_emlite_val_get_value_string(uint32_t h, env_string_t *ret) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(2*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_emlite_env_host_emlite_val_get_value_string((int32_t) (h), ptr);
  *ret = (env_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + sizeof(void*)))) };
}

void emlite_env_host_emlite_val_get_value_string_utf16(uint32_t h, env_list_u16_t *ret) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(2*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_emlite_env_host_emlite_val_get_value_string_utf16((int32_t) (h), ptr);
  *ret = (env_list_u16_t) { (uint16_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + sizeof(void*)))) };
}

void emlite_env_host_emlite_val_typeof(uint32_t h, env_string_t *ret) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(2*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_emlite_env_host_emlite_val_typeof((int32_t) (h), ptr);
  *ret = (env_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + sizeof(void*)))) };
}

void emlite_env_host_emlite_val_push(uint32_t arr, uint32_t val) {
  __wasm_import_emlite_env_host_emlite_val_push((int32_t) (arr), (int32_t) (val));
}

uint32_t emlite_env_host_emlite_val_get(uint32_t obj, uint32_t idx) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_get((int32_t) (obj), (int32_t) (idx));
  return (uint32_t) (ret);
}

void emlite_env_host_emlite_val_set(uint32_t obj, uint32_t idx, uint32_t val) {
  __wasm_import_emlite_env_host_emlite_val_set((int32_t) (obj), (int32_t) (idx), (int32_t) (val));
}

bool emlite_env_host_emlite_val_has(uint32_t obj, uint32_t key) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_has((int32_t) (obj), (int32_t) (key));
  return ret;
}

bool emlite_env_host_emlite_val_not(uint32_t h) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_not((int32_t) (h));
  return ret;
}

bool emlite_env_host_emlite_val_is_string(uint32_t h) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_is_string((int32_t) (h));
  return ret;
}

bool emlite_env_host_emlite_val_is_number(uint32_t h) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_is_number((int32_t) (h));
  return ret;
}

bool emlite_env_host_emlite_val_is_bool(uint32_t h) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_is_bool((int32_t) (h));
  return ret;
}

bool emlite_env_host_emlite_val_gt(uint32_t a, uint32_t b) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_gt((int32_t) (a), (int32_t) (b));
  return ret;
}

bool emlite_env_host_emlite_val_gte(uint32_t a, uint32_t b) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_gte((int32_t) (a), (int32_t) (b));
  return ret;
}

bool emlite_env_host_emlite_val_lt(uint32_t a, uint32_t b) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_lt((int32_t) (a), (int32_t) (b));
  return ret;
}

bool emlite_env_host_emlite_val_lte(uint32_t a, uint32_t b) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_lte((int32_t) (a), (int32_t) (b));
  return ret;
}

bool emlite_env_host_emlite_val_equals(uint32_t a, uint32_t b) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_equals((int32_t) (a), (int32_t) (b));
  return ret;
}

bool emlite_env_host_emlite_val_strictly_equals(uint32_t a, uint32_t b) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_strictly_equals((int32_t) (a), (int32_t) (b));
  return ret;
}

bool emlite_env_host_emlite_val_instanceof(uint32_t a, uint32_t b) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_instanceof((int32_t) (a), (int32_t) (b));
  return ret;
}

uint32_t emlite_env_host_emlite_val_obj_call(uint32_t obj, env_string_t *method, uint32_t argv) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_obj_call((int32_t) (obj), (uint8_t *) (*method).ptr, (*method).len, (int32_t) (argv));
  return (uint32_t) (ret);
}

bool emlite_env_host_emlite_val_obj_has_own_prop(uint32_t obj, env_string_t *prop) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_obj_has_own_prop((int32_t) (obj), (uint8_t *) (*prop).ptr, (*prop).len);
  return ret;
}

uint32_t emlite_env_host_emlite_val_construct_new(uint32_t ctor, uint32_t argv) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_construct_new((int32_t) (ctor), (int32_t) (argv));
  return (uint32_t) (ret);
}

uint32_t emlite_env_host_emlite_val_func_call(uint32_t fn, uint32_t argv) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_func_call((int32_t) (fn), (int32_t) (argv));
  return (uint32_t) (ret);
}

void emlite_env_host_emlite_val_inc_ref(uint32_t h) {
  __wasm_import_emlite_env_host_emlite_val_inc_ref((int32_t) (h));
}

void emlite_env_host_emlite_val_dec_ref(uint32_t h) {
  __wasm_import_emlite_env_host_emlite_val_dec_ref((int32_t) (h));
}

void emlite_env_host_emlite_val_throw(uint32_t h) {
  __wasm_import_emlite_env_host_emlite_val_throw((int32_t) (h));
}

void emlite_env_host_emlite_print_object_map(void) {
  __wasm_import_emlite_env_host_emlite_print_object_map();
}

void emlite_env_host_emlite_reset_object_map(void) {
  __wasm_import_emlite_env_host_emlite_reset_object_map();
}

uint32_t emlite_env_host_emlite_val_make_callback(uint32_t fidx, uint32_t data) {
  int32_t ret = __wasm_import_emlite_env_host_emlite_val_make_callback((int32_t) (fidx), (int32_t) (data));
  return (uint32_t) (ret);
}

__attribute__((__export_name__("emlite:env/dyncall@0.1.0#apply")))
int32_t __wasm_export_exports_emlite_env_dyncall_apply(int32_t arg, int32_t arg0, int32_t arg1) {
  uint32_t ret = exports_emlite_env_dyncall_apply((uint32_t) (arg), (uint32_t) (arg0), (uint32_t) (arg1));
  return (int32_t) (ret);
}

__attribute__((__export_name__("emlite:env/dyncall@0.1.0#emlite-target")))
int32_t __wasm_export_exports_emlite_env_dyncall_emlite_target(void) {
  int32_t ret = exports_emlite_env_dyncall_emlite_target();
  return ret;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_env(void);
__attribute__((used))
void __component_type_object_force_link_env_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_env();
}
